services:
  backend:
    build: ./backend
    volumes:
      - ./backend/model:/app/model
      - ./backend/data.jsonl:/app/data.jsonl  # optional if dataset is outside
    ports:
      - "8000:8000"
